name: qgt

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data/db

  keycloak:
    command: "start-dev"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    restart: always

volumes:
  mongodb:
